### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aimanoj73** [PraneethKarnena/mca-web-scraping#3]
Error: 'NoneType' object has no attribute 'find_all'

**Comment by praneethk19** [comment]
The endpoint of the MCA website has been modified and hence the error. I have now changed the data source URL and it is working fine. 
![Screenshot from 2021-07-17 21-35-42](https://user-images.githubusercontent.com/17551534/126042954-6fcb89c9-170e-4498-905e-e66cb7846b21.png)
